version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directory: /otel
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
    groups:
      go.opentelemetry.io:
        patterns:
          - go.opentelemetry.io/*

  - package-ecosystem: github-actions
    directory: /
    labels:
      - Skip-Changelog
    schedule:
      interval: weekly
