version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    labels:
      - Skip-Changelog
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /otel
    labels:
      - Skip-Changelog
    schedule:
      interval: daily

  - package-ecosystem: github-actions
    directory: /
    labels:
      - Skip-Changelog
    schedule:
      interval: daily
